### ISSUE TITLE
Port to ES5?

### ISSUE THREAD

**Issue by ericelliott** [ericelliott/redux-dsm#9]
As mentioned [elsewhere](https://github.com/ericelliott/redux-dsm/issues/7) ES6 is going to be troublesome because many platforms won't support ES6.

This library uses a generator, which means that compiling to ES5 will mean that the targets will need to have a generator runtime installed.

We can avoid all the mess of compiling if we just write the module in ES5 to begin with. =)

Pros? Cons?

**Comment by zouhir** [comment]
I noticed that people aren't too happy about having the module in ES6 and I gave it another thought after that discussion.
My short answer would be: Yes, I agree on writing it in ES5 and keeping it in the mainstream like other open source packages I usually look at their code.

Pros: 
- People will just plug&play no build or effort required.
- less choices and libraries grabbed by users and community love that.
- We will save a lot of time discussing things with people and trying to proof which point is more valid.

Questions in my mind that will help me a lot understanding this:
- When you use dsm after installing from npm, will build tools get issues transpiring and injecting required code in the bundle in ES5?
- which one is more recommended [Babel Polyfill](http://babeljs.io/docs/usage/polyfill/) or [Runtime transform ponyfill](http://babeljs.io/docs/plugins/transform-runtime/) would work? I have never user generators in prod before :)

**Comment by FredyC** [comment]
What about just not using generators? It seems to me like a backward thinking to ditch whole ES6 just because you cannot use generators. Currently the general support of ES6 is very good already. Of course there will be IE browser which will never support any of ES6 stuff, that's the fact, but this browser is used less and less, so it shouldn't be a big problem in long run.

@zouhir The Babel Polyfill wont solve a thing. It contains things which are not part of language (eg. Array.prototype.includes) that are attached to global objects. Generators are the language features, so you need transform-runtime plugin and it will be included in resulting code.

> People will just plug&play no build or effort required.

As long this is solved prebuilt package is in NPM, this pro isn't really relevant pro.

> less choices and libraries grabbed by users and community love that.

Not sure what that means. You are implying that people rather pick pure ES5 modules?

**Comment by zouhir** [comment]
@FredyC Thanks for collaborating, you obviously aware of something I'm not 💯 aware of.

Let's tackle the problem together:
> People will just plug&play no build or effort required.
Here there are 2 options. Either I put `Babel` back or we `re-write in ES5`

> less choices and libraries grabbed by users and community love that.
> Not sure what that means. You are implying that people rather pick pure ES5 modules?
No my friend, here I'm implying that developers will most likely abandon a package if there's a mandatory build step. If every library we pull from npm we need to build it, our life might become harder after 5 packages and our goal is to make our and anyones life easier.

Focusing on what's really important.

> Obvious con here is increased package size and some people say that it's rather badly written and not very performant.
I agree with you on this con, many cheaper (package size wise) options can replace generators.

Thanks to both of you and @ericelliott for this discussing. already learned something new.

**Comment by FredyC** [comment]
Yes I agree that additional build step for a consumer of package is just bothersome. You've got those two options essentially right. Since @ericelliott essentially hates babel, that's kinda reduced to a single option and this issue is obsolete.

Main question to ask here is: Do you want to go with all the trouble of transpiling?

If not, then rewriting to ES5 is kinda only option here.

**Comment by ericelliott** [comment]
I don't hate babel, but the generator runtime would bloat user bundles a bit too much for my liking. Generator's can't work in ES5 without a runtime polyfill.

My only other concern is that this is a fairly small library... it may be easier to author in ES5 than to build a dist file for ES5 from ES6.

**Comment by Sigmus** [comment]
Less is more! Plus it will be interesting to learn from the rewrite. Generators articles usually teach rewrites from ES5 to generators, not the other way around.

**Comment by ericelliott** [comment]
Would one of you like to review this? I have Master protected so all PRs need at least one review: https://github.com/ericelliott/redux-dsm/pull/10

**Comment by FredyC** [comment]
Well once again, why not to just ditch generators and keep rest of the code in ES6? I don't follow your logic all or nothing here...

**Comment by FredyC** [comment]
> Also, iOS <= 9 don't support arrow functions, and as others have pointed out, build tools ignore node_modules, so distributing the ES6 version is probably not a great idea. );

It's good thing to have ES6 build because most environments can support that just out of the box. I don't an idea of limiting own abilities of writing ES6 because some old platforms cannot support it.

Conclusion: I think that transpiling is currently inevitable to make everyone happy

**Comment by ericelliott** [comment]
> It's good thing to have ES6 build because most environments can support that just out of the box. I don't like limiting own abilities of writing ES6 because some old platforms cannot support it.

iOS 10 was just released last month. **Almost all iOS devices** in the wild use iOS 9 or older.

**Comment by Sigmus** [comment]
@ericelliott I can review it (never done it).

**Comment by zouhir** [comment]
I understand so fat that our plan can be similar to this:
- convert the generator function to aproperiate callbacks
- transpile to ES5 and point package.json to /dist/

Please let me know if I'm missing something

**Comment by Sigmus** [comment]
I understood something different:
* convert everything to ES5
* no transpile step necessary

**Comment by zouhir** [comment]
@Sigmus probably, I'm bit confused. I was thinking same as you at first then I felt that babel and ES6 can be fine as long as we ditch generators.

Let's get @ericelliott to make the call. 
for me, once generator function is converted the rest is a matter of converting => to functions, const to var, and ES5ify spread and rest stuff.

**Comment by FredyC** [comment]
@Sigmus 
> * convert everything to ES5
> * no transpile step necessary

This is just safe path, nothing else. If everyone would choose this path, the ES6 would not thrive that much as it does. Luckily they did not and I really grateful for that because ES6 really makes some tasks easier and/or more readable.

Also consider what will happen in a moment, when ES6 is no longer a problem to overcome, but becomes a standard. Are you going to rewrite from ES5 back to ES6? I doubt about that.

That transpile step you can talking about, it doesn't need to be complicated really. Just add npm script with `"build": "babel src -d dist"` and everything is just fine. No need to rewrite manually really.

**Comment by zouhir** [comment]
Happy Friday folks! Yeah @FredyC opinion makes a lot of sense to me.

**Comment by ericelliott** [comment]
Looking at the code again, we'd lose a lot of interesting function signature data if we convert to ES5.

I think we should port the generator to an iterative form (using normal ES5 loops), and compile the rest to ES5.

**Comment by zouhir** [comment]
Hello folks. I'm sorry I got busy with a lot of things, I haven't forgot about this and will pick it up and be involved better after my exam week :) wait for me next week! 💯  Thanks!

**Comment by dash-** [comment]
I've submitted a pull request replacing the generator function with different (and simpler) logic.  Please review.

https://github.com/ericelliott/redux-dsm/pull/11

> I'm something of an outsider, so I'm not 100% sure of what the getStates requirements
> were.  But looking at the logic and test cases, simply flattening the array and chunking
> (with size=2) should be preferable over a complex, recursive replacement.
>
> Passes tests. If this is not an adequate replacement, a more complex test should be 
> devised showing more full range of acceptable input/output.
>
> David Ash (tw: netjumpio)

**Comment by dash-** [comment]
@ericelliott pointed out the approach of #11 wouldn't be forward-compatible with planned future features, so I reworked it as a recursive reducer. https://github.com/ericelliott/redux-dsm/pull/12/files

**Comment by dash-** [comment]
We have now completed the transition to ES5 by rewriting the function generator (#12) and implementing Babel transpiling (#14).  I vote to close this issue.

**Comment by ericelliott** [comment]
Published as `v1.0.2`
